// <auto-generated />
using System;
using Airplane_UI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Airplane_API.Migrations
{
    [DbContext(typeof(AirplaneManagementSystemContext))]
    partial class AirplaneManagementSystemContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Airplane_API.Entities.AirlineCore.Aircraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AirlineId")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TailNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("AirlineId");

                    b.HasIndex("TailNumber")
                        .IsUnique();

                    b.ToTable("Aircrafts", (string)null);
                });

            modelBuilder.Entity("Airplane_API.Entities.AirlineCore.Airline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IATA_Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("IATA_Code")
                        .IsUnique();

                    b.ToTable("Airlines", (string)null);
                });

            modelBuilder.Entity("Airplane_API.Entities.AirlineCore.Airport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IATA_Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("IATA_Code")
                        .IsUnique();

                    b.ToTable("Airports", (string)null);
                });

            modelBuilder.Entity("Airplane_API.Entities.AirlineCore.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AircraftId")
                        .HasColumnType("int");

                    b.Property<int>("AirlineId")
                        .HasColumnType("int");

                    b.Property<int>("DestinationAirportId")
                        .HasColumnType("int");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("OriginAirportId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScheduledArrival")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ScheduledDeparture")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AircraftId");

                    b.HasIndex("AirlineId");

                    b.HasIndex("DestinationAirportId");

                    b.HasIndex("OriginAirportId");

                    b.ToTable("Flights", (string)null);
                });

            modelBuilder.Entity("Airplane_API.Entities.AirlineCore.FlightManifest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FlightId")
                        .HasColumnType("int");

                    b.Property<int>("PassengerId")
                        .HasColumnType("int");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.HasIndex("PassengerId");

                    b.ToTable("FlightManifests", (string)null);
                });

            modelBuilder.Entity("Airplane_API.Entities.AirlineCore.Passenger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Passengers", (string)null);
                });

            modelBuilder.Entity("Airplane_API.Entities.GateAssignments.Gate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GateNumber")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TerminalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TerminalId");

                    b.ToTable("Gates", (string)null);
                });

            modelBuilder.Entity("Airplane_API.Entities.GateAssignments.GateAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("FlightId")
                        .HasColumnType("int");

                    b.Property<int>("GateId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.HasIndex("GateId");

                    b.ToTable("GateAssignments", (string)null);
                });

            modelBuilder.Entity("Airplane_API.Entities.GateAssignments.GroundCrewTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TaskName");

                    b.HasKey("Id");

                    b.ToTable("GroundCrewTeams", (string)null);
                });

            modelBuilder.Entity("Airplane_API.Entities.GateAssignments.Runway", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Runways", (string)null);
                });

            modelBuilder.Entity("Airplane_API.Entities.GateAssignments.RunwaySchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FlightId")
                        .HasColumnType("int");

                    b.Property<int>("RunwayId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScheduledTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.HasIndex("RunwayId");

                    b.ToTable("RunwaySchedules", (string)null);
                });

            modelBuilder.Entity("Airplane_API.Entities.GateAssignments.Terminal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Terminals", (string)null);
                });

            modelBuilder.Entity("Airplane_API.Entities.LuggageMaintnance.BaggageClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CarouselNumber")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TerminalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TerminalId");

                    b.ToTable("BaggageClaims", (string)null);
                });

            modelBuilder.Entity("Airplane_API.Entities.LuggageMaintnance.CateringFacilities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ProviderName");

                    b.HasKey("Id");

                    b.ToTable("CateringFacilities", (string)null);
                });

            modelBuilder.Entity("Airplane_API.Entities.LuggageMaintnance.CateringOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FlightId")
                        .HasColumnType("int");

                    b.Property<int>("MealCount")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FlightId")
                        .IsUnique();

                    b.HasIndex("ServiceId");

                    b.ToTable("CateringOrders", (string)null);
                });

            modelBuilder.Entity("Airplane_API.Entities.LuggageMaintnance.LostAndFound", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateFound")
                        .HasColumnType("datetime2");

                    b.Property<string>("ItemDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LostAndFounds", (string)null);
                });

            modelBuilder.Entity("Airplane_API.Entities.LuggageMaintnance.MaintenanceLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AircraftId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaintenanceTaskId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AircraftId");

                    b.HasIndex("MaintenanceTaskId");

                    b.ToTable("MaintenanceLogs", (string)null);
                });

            modelBuilder.Entity("Airplane_API.Entities.LuggageMaintnance.MaintenanceTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("TaskName");

                    b.HasKey("Id");

                    b.ToTable("MaintenanceTasks", (string)null);
                });

            modelBuilder.Entity("Airplane_API.Entities.SecurityGates.AirportStaff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("AirportStaffs", (string)null);
                });

            modelBuilder.Entity("Airplane_API.Entities.SecurityGates.CheckpointLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CheckpointID")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("ReportedWaitTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CheckpointID");

                    b.ToTable("CheckpointLogs", (string)null);
                });

            modelBuilder.Entity("Airplane_API.Entities.SecurityGates.CustomsDesk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeskNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TerminalID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TerminalID");

                    b.ToTable("CustomsDesks", (string)null);
                });

            modelBuilder.Entity("Airplane_API.Entities.SecurityGates.SecurityCheckpoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TerminalID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TerminalID");

                    b.ToTable("SecurityCheckpoints", (string)null);
                });

            modelBuilder.Entity("Airplane_API.Entities.SecurityGates.SecurityIncident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedStaffID")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReportDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssignedStaffID");

                    b.ToTable("SecurityIncidents", (string)null);
                });

            modelBuilder.Entity("Airplane_API.Entities.SecurityGates.StaffShift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedCheckpointID")
                        .HasColumnType("int");

                    b.Property<int?>("AssignedDeskID")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("StaffID")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssignedCheckpointID");

                    b.HasIndex("AssignedDeskID");

                    b.HasIndex("StaffID");

                    b.ToTable("StaffShifts", (string)null);
                });

            modelBuilder.Entity("Airplane_API.Entities.AirlineCore.Aircraft", b =>
                {
                    b.HasOne("Airplane_API.Entities.AirlineCore.Airline", "Airline")
                        .WithMany()
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Airline");
                });

            modelBuilder.Entity("Airplane_API.Entities.AirlineCore.Flight", b =>
                {
                    b.HasOne("Airplane_API.Entities.AirlineCore.Aircraft", "Aircraft")
                        .WithMany("Flights")
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Airplane_API.Entities.AirlineCore.Airline", "Airline")
                        .WithMany()
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Airplane_API.Entities.AirlineCore.Airport", "DestinationAirport")
                        .WithMany()
                        .HasForeignKey("DestinationAirportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Airplane_API.Entities.AirlineCore.Airport", "OriginAirport")
                        .WithMany()
                        .HasForeignKey("OriginAirportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aircraft");

                    b.Navigation("Airline");

                    b.Navigation("DestinationAirport");

                    b.Navigation("OriginAirport");
                });

            modelBuilder.Entity("Airplane_API.Entities.AirlineCore.FlightManifest", b =>
                {
                    b.HasOne("Airplane_API.Entities.AirlineCore.Flight", "Flight")
                        .WithMany("FlightManifests")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Airplane_API.Entities.AirlineCore.Passenger", "Passenger")
                        .WithMany("FlightManifests")
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Flight");

                    b.Navigation("Passenger");
                });

            modelBuilder.Entity("Airplane_API.Entities.GateAssignments.Gate", b =>
                {
                    b.HasOne("Airplane_API.Entities.GateAssignments.Terminal", "Terminal")
                        .WithMany("Gates")
                        .HasForeignKey("TerminalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Terminal");
                });

            modelBuilder.Entity("Airplane_API.Entities.GateAssignments.GateAssignment", b =>
                {
                    b.HasOne("Airplane_API.Entities.AirlineCore.Flight", "Flight")
                        .WithMany("GateAssignments")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Airplane_API.Entities.GateAssignments.Gate", "Gate")
                        .WithMany("GateAssignments")
                        .HasForeignKey("GateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Flight");

                    b.Navigation("Gate");
                });

            modelBuilder.Entity("Airplane_API.Entities.GateAssignments.RunwaySchedule", b =>
                {
                    b.HasOne("Airplane_API.Entities.AirlineCore.Flight", "Flight")
                        .WithMany("RunwaySchedules")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Airplane_API.Entities.GateAssignments.Runway", "Runway")
                        .WithMany("RunwaySchedules")
                        .HasForeignKey("RunwayId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Flight");

                    b.Navigation("Runway");
                });

            modelBuilder.Entity("Airplane_API.Entities.LuggageMaintnance.BaggageClaim", b =>
                {
                    b.HasOne("Airplane_API.Entities.GateAssignments.Terminal", "Terminal")
                        .WithMany("BaggageClaims")
                        .HasForeignKey("TerminalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Terminal");
                });

            modelBuilder.Entity("Airplane_API.Entities.LuggageMaintnance.CateringOrder", b =>
                {
                    b.HasOne("Airplane_API.Entities.AirlineCore.Flight", "Flight")
                        .WithOne("CateringOrder")
                        .HasForeignKey("Airplane_API.Entities.LuggageMaintnance.CateringOrder", "FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Airplane_API.Entities.LuggageMaintnance.CateringFacilities", "CateringFacilities")
                        .WithMany("CateringOrders")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CateringFacilities");

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("Airplane_API.Entities.LuggageMaintnance.MaintenanceLog", b =>
                {
                    b.HasOne("Airplane_API.Entities.AirlineCore.Aircraft", "Aircraft")
                        .WithMany("MaintenanceLogs")
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Airplane_API.Entities.LuggageMaintnance.MaintenanceTask", "MaintenanceTask")
                        .WithMany("MaintenanceLogs")
                        .HasForeignKey("MaintenanceTaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aircraft");

                    b.Navigation("MaintenanceTask");
                });

            modelBuilder.Entity("Airplane_API.Entities.SecurityGates.CheckpointLog", b =>
                {
                    b.HasOne("Airplane_API.Entities.SecurityGates.SecurityCheckpoint", "SecurityCheckpoint")
                        .WithMany("CheckpointLogs")
                        .HasForeignKey("CheckpointID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SecurityCheckpoint");
                });

            modelBuilder.Entity("Airplane_API.Entities.SecurityGates.CustomsDesk", b =>
                {
                    b.HasOne("Airplane_API.Entities.GateAssignments.Terminal", "Terminal")
                        .WithMany("CustomsDesks")
                        .HasForeignKey("TerminalID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Terminal");
                });

            modelBuilder.Entity("Airplane_API.Entities.SecurityGates.SecurityCheckpoint", b =>
                {
                    b.HasOne("Airplane_API.Entities.GateAssignments.Terminal", "Terminal")
                        .WithMany("SecurityCheckpoints")
                        .HasForeignKey("TerminalID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Terminal");
                });

            modelBuilder.Entity("Airplane_API.Entities.SecurityGates.SecurityIncident", b =>
                {
                    b.HasOne("Airplane_API.Entities.SecurityGates.AirportStaff", "AssignedStaff")
                        .WithMany("SecurityIncidentsHandled")
                        .HasForeignKey("AssignedStaffID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedStaff");
                });

            modelBuilder.Entity("Airplane_API.Entities.SecurityGates.StaffShift", b =>
                {
                    b.HasOne("Airplane_API.Entities.SecurityGates.SecurityCheckpoint", "AssignedCheckpoint")
                        .WithMany("AssignedShifts")
                        .HasForeignKey("AssignedCheckpointID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Airplane_API.Entities.SecurityGates.CustomsDesk", "AssignedDesk")
                        .WithMany("AssignedShifts")
                        .HasForeignKey("AssignedDeskID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Airplane_API.Entities.SecurityGates.AirportStaff", "AirportStaff")
                        .WithMany("StaffShifts")
                        .HasForeignKey("StaffID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AirportStaff");

                    b.Navigation("AssignedCheckpoint");

                    b.Navigation("AssignedDesk");
                });

            modelBuilder.Entity("Airplane_API.Entities.AirlineCore.Aircraft", b =>
                {
                    b.Navigation("Flights");

                    b.Navigation("MaintenanceLogs");
                });

            modelBuilder.Entity("Airplane_API.Entities.AirlineCore.Flight", b =>
                {
                    b.Navigation("CateringOrder")
                        .IsRequired();

                    b.Navigation("FlightManifests");

                    b.Navigation("GateAssignments");

                    b.Navigation("RunwaySchedules");
                });

            modelBuilder.Entity("Airplane_API.Entities.AirlineCore.Passenger", b =>
                {
                    b.Navigation("FlightManifests");
                });

            modelBuilder.Entity("Airplane_API.Entities.GateAssignments.Gate", b =>
                {
                    b.Navigation("GateAssignments");
                });

            modelBuilder.Entity("Airplane_API.Entities.GateAssignments.Runway", b =>
                {
                    b.Navigation("RunwaySchedules");
                });

            modelBuilder.Entity("Airplane_API.Entities.GateAssignments.Terminal", b =>
                {
                    b.Navigation("BaggageClaims");

                    b.Navigation("CustomsDesks");

                    b.Navigation("Gates");

                    b.Navigation("SecurityCheckpoints");
                });

            modelBuilder.Entity("Airplane_API.Entities.LuggageMaintnance.CateringFacilities", b =>
                {
                    b.Navigation("CateringOrders");
                });

            modelBuilder.Entity("Airplane_API.Entities.LuggageMaintnance.MaintenanceTask", b =>
                {
                    b.Navigation("MaintenanceLogs");
                });

            modelBuilder.Entity("Airplane_API.Entities.SecurityGates.AirportStaff", b =>
                {
                    b.Navigation("SecurityIncidentsHandled");

                    b.Navigation("StaffShifts");
                });

            modelBuilder.Entity("Airplane_API.Entities.SecurityGates.CustomsDesk", b =>
                {
                    b.Navigation("AssignedShifts");
                });

            modelBuilder.Entity("Airplane_API.Entities.SecurityGates.SecurityCheckpoint", b =>
                {
                    b.Navigation("AssignedShifts");

                    b.Navigation("CheckpointLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
