using Airplane_API.Entities.Base;

/// <summary>
/// Defines a specific physical security screening location within a terminal.
/// </summary>
public class SecurityCheckpoint : BaseEntity
{
    /// <summary>
    /// Foreign Key linking the checkpoint to its parent terminal.
    /// </summary>
    public int TerminalID { get; set; }

    /// <summary>
    /// A descriptive name for the checkpoint (e.g., 'A-North Security').
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// The operational status of the checkpoint (e.g., 'Open', 'Closed', 'Reduced Staff').
    /// </summary>
    public string Status { get; set; }


    /// <summary>
    /// Navigation property to the parent Terminal.
    /// </summary>
    public Terminal Terminal { get; set; }

    /// <summary>
    /// Collection of operational logs and wait times generated by this checkpoint (1-to-Many).
    /// </summary>
    public ICollection<CheckpointLog> CheckpointLogs { get; set; } = new List<CheckpointLog>();

    /// <summary>
    /// Collection of staff shifts assigned to this checkpoint (1-to-Many).
    /// </summary>
    public ICollection<StaffShift> AssignedShifts { get; set; } = new List<StaffShift>();
}